"use client"

import { type FormEvent, useEffect, useMemo, useState } from "react"
import { CopyIcon, Trash2Icon } from "lucide-react"
import { toast } from "sonner"

import { CodeEditor } from "@/components/code-editor"
import { HttpStatusBadge } from "@/components/http-status-badge"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import {
  MOCK_METHODS,
  mockEndpointPath,
  parseJsonBody,
  validateMockDraft,
  type MockEndpoint,
  type MockMethod,
} from "@/lib/mock-endpoints"
import {
  deleteMockEndpoint,
  listOwnMockEndpoints,
  saveMockEndpoint,
} from "@/lib/supabase/mock-endpoints"

const DEFAULT_BODY = `{
  "ok": true,
  "message": "Generated by Quality Central"
}`

export function MockServerDashboard() {
  const [slug, setSlug] = useState("failed-orders")
  const [method, setMethod] = useState<MockMethod>("GET")
  const [statusCode, setStatusCode] = useState("500")
  const [body, setBody] = useState(DEFAULT_BODY)
  const [endpoints, setEndpoints] = useState<MockEndpoint[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const origin = useMemo(() => {
    if (typeof window === "undefined") {
      return ""
    }
    return window.location.origin
  }, [])

  const previewPath = mockEndpointPath(
    slug.trim().toLowerCase() || "your-slug"
  )

  useEffect(() => {
    let cancelled = false

    async function load() {
      try {
        const rows = await listOwnMockEndpoints()
        if (!cancelled) {
          setEndpoints(rows)
        }
      } catch (loadError) {
        if (!cancelled) {
          setError(
            loadError instanceof Error
              ? loadError.message
              : "Could not load mock endpoints."
          )
        }
      } finally {
        if (!cancelled) {
          setLoading(false)
        }
      }
    }

    void load()
    return () => {
      cancelled = true
    }
  }, [])

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError(null)

    const json = parseJsonBody(body)
    if (!json.ok) {
      setError(json.error)
      return
    }

    const parsed = validateMockDraft({
      slug,
      method,
      statusCode,
      responseBody: json.value,
    })
    if (!parsed.ok) {
      setError(parsed.error)
      return
    }

    setSaving(true)
    try {
      const saved = await saveMockEndpoint(parsed.draft)
      setEndpoints((current) => [
        saved,
        ...current.filter(
          (item) =>
            !(item.slug === saved.slug && item.method === saved.method)
        ),
      ])
      toast.success("Mock endpoint saved", {
        description: `${saved.method} ${mockEndpointPath(saved.slug)} → ${saved.statusCode}`,
        id: "mock-endpoint-save",
      })
    } catch (saveError) {
      const message =
        saveError instanceof Error
          ? saveError.message
          : "Could not save the endpoint."
      setError(message)
      toast.error("Save failed", {
        description: message,
        id: "mock-endpoint-save",
      })
    } finally {
      setSaving(false)
    }
  }

  async function onDelete(endpoint: MockEndpoint) {
    try {
      await deleteMockEndpoint(endpoint.id)
      setEndpoints((current) =>
        current.filter((item) => item.id !== endpoint.id)
      )
      toast.message("Endpoint removed", {
        description: `${endpoint.method} /${endpoint.slug}`,
        id: "mock-endpoint-delete",
      })
    } catch (deleteError) {
      toast.error("Delete failed", {
        description:
          deleteError instanceof Error
            ? deleteError.message
            : "Could not delete the endpoint.",
        id: "mock-endpoint-delete",
      })
    }
  }

  function copyUrl(endpoint: MockEndpoint) {
    const url = `${origin}${mockEndpointPath(endpoint.slug)}`
    void navigator.clipboard.writeText(url)
    toast.success("URL copied", {
      description: url,
      id: "mock-endpoint-copy",
    })
  }

  return (
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
      <Card>
        <CardHeader>
          <CardTitle>Define an endpoint</CardTitle>
          <CardDescription>
            Students can point Postman or Playwright at the live URL after you
            save.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit} className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="mock-slug">URL slug</Label>
              <Input
                id="mock-slug"
                value={slug}
                onChange={(event) => setSlug(event.target.value)}
                placeholder="failed-orders"
                autoComplete="off"
              />
              <p className="font-mono text-xs text-muted-foreground">
                {origin}
                {previewPath}
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              <div className="grid gap-2">
                <Label htmlFor="mock-method">HTTP method</Label>
                <Select
                  value={method}
                  onValueChange={(value) => setMethod(value as MockMethod)}
                >
                  <SelectTrigger id="mock-method" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {MOCK_METHODS.map((item) => (
                      <SelectItem key={item} value={item}>
                        {item}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="mock-status">Desired status code</Label>
                <Input
                  id="mock-status"
                  inputMode="numeric"
                  value={statusCode}
                  onChange={(event) => setStatusCode(event.target.value)}
                  placeholder="200"
                />
              </div>
            </div>

            <div className="grid gap-2">
              <Label htmlFor="mock-body">JSON response body</Label>
              <div className="overflow-hidden rounded-lg border border-border">
                <CodeEditor
                  value={body}
                  language="json"
                  height={220}
                  ariaLabel="JSON response body"
                  onChange={(value) => setBody(value ?? "")}
                />
              </div>
            </div>

            {error ? (
              <p className="text-sm text-destructive">{error}</p>
            ) : null}

            <Button type="submit" disabled={saving}>
              {saving ? "Saving…" : "Save endpoint"}
            </Button>
          </form>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Your live mocks</CardTitle>
          <CardDescription>
            Same slug can expose different methods. A missing method returns
            405.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {loading ? (
            <p className="text-sm text-muted-foreground">Loading endpoints…</p>
          ) : endpoints.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              No mocks yet. Save one on the left, then run it from Postman or
              the API playground.
            </p>
          ) : (
            <ul className="grid gap-3">
              {endpoints.map((endpoint) => (
                <li
                  key={endpoint.id}
                  className="rounded-lg border border-border/80 bg-muted/20 p-3"
                >
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant="outline" className="font-mono">
                      {endpoint.method}
                    </Badge>
                    <span className="font-mono text-sm">
                      {mockEndpointPath(endpoint.slug)}
                    </span>
                    <HttpStatusBadge status={endpoint.statusCode} />
                  </div>
                  <Textarea
                    readOnly
                    value={JSON.stringify(endpoint.responseBody, null, 2)}
                    className="mt-2 max-h-32 font-mono text-xs"
                  />
                  <div className="mt-2 flex flex-wrap gap-2">
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => copyUrl(endpoint)}
                    >
                      <CopyIcon data-icon="inline-start" />
                      Copy URL
                    </Button>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      onClick={() => onDelete(endpoint)}
                    >
                      <Trash2Icon data-icon="inline-start" />
                      Delete
                    </Button>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
